### PR TITLE
Added missing resource from DscResourcesToExport

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

Added `WSManConfig` to `DscResourcesToExport` in manifest.

@johlju - would you mind reviewing this one for me? I missed this from the manifest so it doesn't appear on PSGallery in the list of DSC Resources exported.

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/plagueho/wsmandsc/46)

### CODE REVIEW

**Comment by Outek** [comment]
Hi @PlagueHO 

I think, you only modified the CHANGELOG.md?

**Comment by PlagueHO** [comment]
@johlju! Doh - forgot to press save before committing. Fixed.

**Comment by johlju** [comment]
@Outek had already approved this PR but I just cleared my comments to get the status check approved.  @Outek thank you for reviewing! Much appreciated! 😃

**Comment by PlagueHO** [comment]
Thanks @Outek and @johlju!

**Pull request merged**
